apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hupynl02p-python 
  janus-idp.io/tekton: hupynl02p-python
  backstage.io/kubernetes-id: hupynl02p-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hupynl02p-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  